name: latteconnect
description: "Aplicativo Android em Flutter do latteConect para conectar nutrizes doadoras, hospitais e familias que precisam de leite humano."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
